version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:4.0.7-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/ssl:/etc/rabbitmq/ssl
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
  main_backend:
    build: ./main_backend
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy

  ecg_digitalizer:
    build: ./ecg_digitalizer
    ports:
      - "8001:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy

  diagnostic_backend:
    build: ./diagnostic_backend
    ports:
      - "8002:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  rabbitmq_data:
